version: "3.9"

services:
  www:
    build:
      context: .
      dockerfile: ./Docker/www/Dockerfile
    expose:
      - 5000
    volumes:
      - ./app/:/app/:ro
    working_dir: /app

  nginx:
    build:
      context: ./Docker/nginx
    ports:
      - "80:80"
    depends_on:
      - www
