version: "3.9"

services:
  www:
    build:
      context: .
      dockerfile: ./Docker/www/Dockerfile
    expose:
      - 5000
    volumes:
      - ./app/:/app/:ro
    working_dir: /

  nginx:
    build:
      context: ./Docker/nginx
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - www
